### ISSUE TITLE
spec2nii anon to also act on a JSON sidecar

### ISSUE THREAD

**Issue by schorschinho** [wtclarke/spec2nii#108]
Hi Will,

I'm tinkering with BIDS-ifying a pretty large dataset with BIDScoin. Currently, I need to run `spec2nii anon` and `spec2nii extract` separately after the conversion to remove PHI from the JSON sidecar. (Need to submit a separate issue in the BIDScoin repository because the `anon` option doesn't seem to get picked up correctly)

Would it be possible to allow the `anon` option to be passed at conversion time so that spec2nii generates de-identified nii and JSON files right away? dcm2niix allows something like this with the `-ba` argument (see https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#General_Usage).

Thanks :)
Georg

**Comment by wtclarke** [comment]
This should be fixed in PR #113 . I'll let you know when it's out.
