### ISSUE TITLE
Add support for converting GE P-files revision 30.0

### ISSUE THREAD

**Issue by hfxcarl** [wtclarke/spec2nii#116]
Our local GE MRI scanner was recently updated to software revision 30., and spec2nii (vers-0.7.0) now fails to convert p-files with error:

> spec2nii.GE.ge_read_pfile.UnknownPfile: Unknown header structure for revision 30.0

If it helps, Mark Mikkelsen recently[ updated Gannet to include support for GE software revision 30.0](https://github.com/markmikkelsen/Gannet/commit/66ff5e76845bd2f435fe918f49fdd843d60a8f3a#diff-aa89c45baf57490bc840fdf9b82ba50201eb69d9bdc25bf21645c639507cf263), which apparently has no major differences from rev29.

Thanks,
Carl

**Comment by wtclarke** [comment]
Fixed in 0.7.1
