### ISSUE TITLE
Does auto conversion support TWIX data from XA50?

### ISSUE THREAD

**Issue by shui5** [wtclarke/spec2nii#126]
Dear William,

I ran the auto conversion 'spec2nii auto FILE' in Minicoda and received the following message.
The TWIX data was acquired using a XA50 machine. Any idea to solve this issue?

Best,

Steve
******************************************************
(my_env) C:\Users\SHUI>spec2nii auto C:\Users\SHUI\Desktop\Siemens_HERC\phantom_20240129\meas_MID00030_FID48369_smm_svs_herc_spdur_v1.dat
C:\Users\SHUI\AppData\Local\miniconda3\envs\my_env\lib\site-packages\spec2nii\spec2nii.py:409: UserWarning: Automatic conversion is an experimental feature. Please verify the output carefully.
  warn('Automatic conversion is an experimental feature. Please verify the output carefully.')
Attempting conversion as Siemens Twix (.dat), evalinfo = 'image'
pymapVBVD version 0.5.6
Software version: VD
Traceback (most recent call last):
  File "C:\Users\SHUI\AppData\Local\miniconda3\envs\my_env\Scripts\spec2nii-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\SHUI\AppData\Local\miniconda3\envs\my_env\lib\site-packages\spec2nii\spec2nii.py", line 696, in main
    spec2nii(*args)
  File "C:\Users\SHUI\AppData\Local\miniconda3\envs\my_env\lib\site-packages\spec2nii\spec2nii.py", line 292, in __init__
    args.func(args)
  File "C:\Users\SHUI\AppData\Local\miniconda3\envs\my_env\lib\site-packages\spec2nii\spec2nii.py", line 421, in auto
    self.twix(args)
  File "C:\Users\SHUI\AppData\Local\miniconda3\envs\my_env\lib\site-packages\spec2nii\spec2nii.py", line 504, in twix
    twixObj = twixObj[args.multiraid - 1]
AttributeError: 'Namespace' object has no attribute 'multiraid'

**Comment by wtclarke** [comment]
Hi Steve,

What happens if you try the same data with the `spec2nii twix` option?

**Comment by shui5** [comment]
Thanks for your prompt response. After running these two lines: spec2nii twix FILE and spec2nii twix -v FILE, I got the following messages. Did I run the twix option correctly?
*************************************
(my_env) C:\Users\SHUI>spec2nii twix C:\Users\SHUI\Desktop\Siemens_HERC\phantom_20240129\meas_MID00030_FID48369_smm_svs_herc_spdur_v1.dat
usage: spec2nii twix [-h] (-v | -e EVALINFO) [-m MULTIRAID] [-q] [-d5 DIM5] [-t5 TAG5] [-d6 DIM6] [-t6 TAG6]
                     [-d7 DIM7] [-t7 TAG7] [--remove_os] [-j] [-f FILEOUT] [-o OUTDIR] [--nifti1]
                     [--override_nucleus OVERRIDE_NUCLEUS [OVERRIDE_NUCLEUS ...]]
                     [--override_frequency OVERRIDE_FREQUENCY [OVERRIDE_FREQUENCY ...]]
                     [--override_dwelltime OVERRIDE_DWELLTIME] [--anon] [--verbose]
                     file
spec2nii twix: error: one of the arguments -v/--view -e/--evalinfo is required

(my_env) C:\Users\SHUI>spec2nii twix -v C:\Users\SHUI\Desktop\Siemens_HERC\phantom_20240129\meas_MID00030_FID48369_smm_svs_herc_spdur_v1.dat
pymapVBVD version 0.5.6
Software version: VD
Contents of file meas_MID00030_FID48369_smm_svs_herc_spdur_v1.dat:
Multiraid file, 2 files found.
Selecting file 2. Use -m option to change.
The file contains these evalinfo flags with dimensions and sizes as follows:
image          :        Col, Cha, Ave           [4096   42  320]

**Comment by wtclarke** [comment]
Yes, the second one gives a hint as to how to run the conversion. try `spec2nii twix -e image FILE`

**Comment by shui5** [comment]
I got this: 'Looking for evalinfo flag image'.
********************************************
(my_env) C:\Users\SHUI>spec2nii twix -e image C:\Users\SHUI\Desktop\Siemens_HERC\phantom_20240129\meas_MID00030_FID48369_smm_svs_herc_spdur_v1.dat
pymapVBVD version 0.5.6
Software version: VD
Converting twix file C:\Users\SHUI\Desktop\Siemens_HERC\phantom_20240129\meas_MID00030_FID48369_smm_svs_herc_spdur_v1.dat.
Looking for evalinfo flag image.
Found data of size (4096, 42, 320).

**Comment by wtclarke** [comment]
there should be a file output. You can control where it outputs to with the other arguments `[-f FILEOUT] [-o OUTDIR]`

**Comment by shui5** [comment]
Great. It works. I see the .nii zip file.
Thank you so much!

**Comment by shui5** [comment]
Hi, William,

Thanks for your help. I was able to convert one of my TWIX data into .nii format but when I tried the next one, I got the following message. Is it something to do with the reshape?
Best,
Steve
**************************************************
(C:\ProgramData\anaconda3) C:\Users\SHUI>spec2nii twix -v C:\Users\SHUI\Desktop\Siemens_HERC\phantom_20240129\meas_MID00032_FID48371_HERMES_GABA_GSH.dat
pymapVBVD version 0.5.6
Software version: VD
Contents of file meas_MID00032_FID48371_HERMES_GABA_GSH.dat:
Multiraid file, 2 files found.
Selecting file 2. Use -m option to change.
The file contains these evalinfo flags with dimensions and sizes as follows:
image          :        Col, Cha, Ave           [4096   42  320]

(C:\ProgramData\anaconda3) C:\Users\SHUI>spec2nii twix -e image C:\Users\SHUI\Desktop\Siemens_HERC\phantom_20240129\meas_MID00032_FID48371_HERMES_GABA_GSH.dat -f HERMES -o C:\Users\SHUI\Desktop\Siemens_HERC\phantom_20240129
pymapVBVD version 0.5.6
Software version: VD
Converting twix file C:\Users\SHUI\Desktop\Siemens_HERC\phantom_20240129\meas_MID00032_FID48371_HERMES_GABA_GSH.dat.
Looking for evalinfo flag image.
Found data of size (4096, 42, 320).
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Scripts\spec2nii-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\spec2nii\spec2nii.py", line 696, in main
    spec2nii(*args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\spec2nii\spec2nii.py", line 292, in __init__
    args.func(args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\spec2nii\spec2nii.py", line 513, in twix
    self.imageOut, self.fileoutNames = process_twix(twixObj,
                                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\spec2nii\Siemens\twixfunctions.py", line 127, in process_twix
    return process_svs(
           ^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\spec2nii\Siemens\twixfunctions.py", line 409, in process_svs
    reord_data, meta_obj, dim_tags = mgs_svs_ed_twix(twixObj, reord_data, meta_obj, dim_tags)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\spec2nii\Siemens\twix_special_case.py", line 188, in mgs_svs_ed_twix
    reord_data = reord_data.T.reshape(orig_shape[::-1]).T
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 55050240 into shape (3,42,4096)

**Comment by wtclarke** [comment]
HI @shui5 , that sequence (the universal editing one) is special cased. See the [handling function](https://github.com/wtclarke/spec2nii/blob/master/spec2nii/Siemens/twix_special_case.py#L123) for more information. Could you tell me how you've set it up and in what order you would expect various editing cases?

**Comment by shui5** [comment]
If I remember correctly, editing pulse-1 was 1.9 ppm, -2 was 4.56 ppm and -off was 7.5 ppm for HERMES (GABA-GSH). Is the order of the editing pulses I used in the protocol different from the script?

**Comment by wtclarke** [comment]
Hi @shui5 , Sorry this slipped my mind. It's also cropped up with another user. Is there any chance you could share some data for me to debug? Ideally something off a phantom so I can add it permanently to the test set (the actual spectra can be junk, I just need the layout and headers).

**Comment by shui5** [comment]
hi @wtclarke , I've shared a set of phantom data (1 HERMES and 1 HERCULES) with you. A link is sent to your email address.
Thank you.

**Comment by wtclarke** [comment]
Hi @shui5,

I'm sorry, I've only just got around to this and I can't download the data. Could you try re-sharing?

**Comment by wtclarke** [comment]
This is fixed as of #130 and will be part of the next release. Do reopen if it continues to be a problem and thanks for the data.
