### ISSUE TITLE
spec2nii support for python 3.13

### ISSUE THREAD

**Issue by marcelzwiers** [wtclarke/spec2nii#153]
Currently scipy v1.13 is a hardcoded requirement of spec2nii, but that version doesn't support python 3.13:

> SciPy 1.14.1 adds support for Python 3.13

**Comment by wtclarke** [comment]
Hi @marcelzwiers , Python 3.13 is now handled (and Scipy is listed as `>=1.13`) as of version `0.8.5`. This should now be available on conda-forge.
