### ISSUE TITLE
Question regarding dicom converter

### ISSUE THREAD

**Issue by bloyl** [wtclarke/spec2nii#17]
Hi,

I'm looking into replacing my FID-A twix based processing pipelines with a FID-A dicom based one which is what brought me here. Seems like a very useful and growing project.

I do have some questions about how best to do these conversions to seamlessly slot into what I currently have but first wanted to know if there is discussion forum for questions or if I should just use this issue?

Thanks!
Luke

**Comment by wexeee** [comment]
Hi @bloyl,

I think Georg Oeltzschner (@schorschinho) has been writing a NIfTI-MRS I/O module for FID-A, so much of the heavy lifting should already be done. See [here](https://github.com/CIC-methods/FID-A/blob/master/inputOutput/io_loadspec_niimrs.m).

If you are looking for somewhere to discuss technical aspects of MRS processing, I would recommend https://forum.mrshub.org/. Feel free to start a thread on there about the best usage of spec2nii and NIfTI-MRS, a number of contributors to the standard are on the forums. For bug reports and specific coding questions, here probably remains the best.

**Comment by bloyl** [comment]
Thanks.

mrshub seems like a great resource and that reader is actually what brought me here.

My initial question is about spec2nii usage so I'll ask here and move future questions to the forum.

I've just been converting some megapress data and when I convert the twix files I get a nifti file with the subspecta (edit-on/edit-off) split out in the last dimension (dim7=2). However when I convert the dicom series the nifti file has the subspectra and n averages combined in the dim5 (dim5=naverages*2).
This seems like what `-t` flag is for but i'm unclear how to use it to get what I want.

So I guess the question is can spec2nii sort these spectra internally or do i need to do it before hand?


Thanks.
Luke

**Comment by wexeee** [comment]
Hi @bloyl Sorry about the delay in replying, I didn't get around to this before going on holiday. You are right that there is this inconsistency in how the DICOM conversion and Twix conversion work. In your DICOM data do you know if there is a good way of identifying from the DICOM headers which the subspectra are and which are the temporal averages? I.e. is there a good way of programatically sorting these into dimensions? Currently it simply takes the multiple DICOM files and assumes a single dynamic dimension with a purpose specified by the `-t` option.

I'm building up some [tools in fsl-mrs](https://git.fmrib.ox.ac.uk/fsl/fsl_mrs/-/blob/master/fsl_mrs/utils/nifti_mrs_tools/reshape.py) that can manipulate NIfTI-MRS files, including the reshaping option needed here. However that one is a bit of a work in progress.

**Comment by wtclarke** [comment]
This is now possible in fsl-mrs using the interactive python libraries. See https://git.fmrib.ox.ac.uk/fsl/fsl_mrs/-/blob/master/fsl_mrs/utils/nifti_mrs_tools/reshape.py. I'll close this issue for now on spec2nii, feel free to reopen if you think that there is a way of sorting the dimensions using the DICOM information in a general way.
