### ISSUE TITLE
spec2nii output unreadable by mricron, fslview, and fslmaths

### ISSUE THREAD

**Issue by dmd** [wtclarke/spec2nii#23]
Adding a spec2nii output file in fslview causes it to crash and spew garbage to the console.

Adding to mricron gives "Warning: the header file is not in NIFTi format".

**Comment by dmd** [comment]
fslmaths, most critically, also cannot read it.

**Comment by dmd** [comment]
e.g.: 
```
$ fslmaths "svs_se TE35.nii.gz" -sqr foo.nii.gz
** ERROR: nifti_convert_nhdr2nim: bad datatype
** ERROR (nifti_image_read): cannot create nifti image from header 'svs_se TE35.nii.gz'
** ERROR: nifti_image_open(svs_se TE35): bad header info
ERROR: failed to open file svs_se TE35
Cannot open volume svs_se TE35 for reading!
```

**Comment by dmd** [comment]
And mri_convert from Freesurfer also doesn't like it.

**Comment by wtclarke** [comment]
Hi @dmd 

Thanks for testing all of these programs. fslview is now deprecated and replaced by [FSLeyes](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSLeyes), for which there is a dedicated [NIfTI-MRS plugin](https://git.fmrib.ox.ac.uk/wclarke/fsleyes-plugin-mrs) (though the plugin is optional). I think the reason fslview cannot open the file is the same as fslmaths, namely that MRS data is complex and neither these programs can cope with complex data. I've had some discussions with the core FSL developers about getting complex data handled in fslmaths, but I don't think it will happen soon.

I'm not familiar with  mri_convert and mricron but I'll take a look to see what is happening with them.

**Comment by wtclarke** [comment]
MRIcroGL ( the newer maintained version of MRIcro) now handles NIfTI-MRS to an extent.
