### ISSUE TITLE
Dicom image to NiFTI

### ISSUE THREAD

**Issue by lenn19** [wtclarke/spec2nii#24]
Hi @wtclarke,

I try to use the segmentation of fsl_mrs. Therefor I need to convert my T1 images to NiFTI files. If I try to use "spec2nii dicom /filepath/to/directory" I get an error message with the "ROWS"   
_File "/home/labor/.local/anaconda3/lib/python3.8/site-packages/spec2nii/dicomfunctions.py", line 27, in svs_or_CSI
    rows = img.csa_header['tags']['Rows']['items'][0]
KeyError: 'Rows'_

I also tried to use the twix T1-file that I exportet. I also get an error trying this. 
_/home/labor/sciebo/Bachelorarbeit/Porgramm/Desktop/20211118/20211118_Bedarf_Lennart/BEDARF_LENNART_20211118_JB02/JB_TMP_20211118_155400_190000/T1_MPRAGE_SAG_P2_ISO_1MM_0002_

Do you have any suggestions what I can do? Maybe I don't need a NiFTI file for segmentation in fsl_mrs?

Thanks for your help.
Best reguards

**Comment by wtclarke** [comment]
Hi @lenn19 I'd use [dcm2niix](https://github.com/rordenlab/dcm2niix) to convert DICOM images to nifti. Not spec2nii.
