### ISSUE TITLE
Philips SOP Class UID error

### ISSUE THREAD

**Issue by wtclarke** [wtclarke/spec2nii#51]
I have faced the same problem. In addition, when I use the spec2nii philips_dcm function, I get the following error:
"Media Storage SOP Class UID {media_storage_class} not recognised as spectroscopy" Kindly Help

_Originally posted by @karthikrrish in https://github.com/wtclarke/spec2nii/issues/40#issuecomment-1251270432_

**Comment by wtclarke** [comment]
https://github.com/wtclarke/spec2nii/issues/40#issuecomment-1251819092

**Comment by wtclarke** [comment]
Hi @karthikrrish,

I've moved this to a new issue as it is unrelated to the issue you posted in.

The SOP Class UID your data has '1.2.840.10008.5.1.4.1.1.66' is not a recognised spectroscopy format. I think this is because you are loading all DICOM files in the directory which contains some 'raw data' and maybe some imaging as well. Can you try targeting just the MRS data in that directory?

In the future I'll make it so that spec2nii just skips these files instead of crashing.

**Comment by karthikrrish** [comment]
Hi Clarke,
Thank you for the swift response. I appreciate it. I did try targeting the MRS data in the directory. This is what happened:
![image](https://user-images.githubusercontent.com/66436939/191178801-3e799862-4314-4094-aff6-362101894110.png)

It Just says header extension validated and stops after that. I don't get a nii file to work on. Maybe I am doing something incorrectly. Please take a look at this and guide me.

**Comment by wtclarke** [comment]
That looks like it's completed successfully without an error. The file should appear in the current directory (i.e. the directory you see when you run `pwd`). You can try specifying a different location using the `-o` argument.

**Comment by karthikrrish** [comment]
Thank you. Adding the -o option solved the problem. Thanks for all the help!
