### ISSUE TITLE
Issue with a special sequence from Jamie Near @XA30

### ISSUE THREAD

**Issue by bkossows** [wtclarke/spec2nii#67]
Hi Will,
I have difficulties to properly convert & processed the data from Jamie Near's SPECIAL. My Prisma has XA30 Numaris. I've already emailed @jamienear about the same problem in FID-A. I have enabled "in line reference" for those scans, so my TWIX file has 2 frames. The spectra look perfect on the console and also when I work with RDA files. I can provide You the original TWIX file in the private message, if that's ok.
![special_twix](https://user-images.githubusercontent.com/28865905/218102874-0c7fd730-3693-4aba-9b62-3a16c08db53e.png)
TWIX
![special_rda](https://user-images.githubusercontent.com/28865905/218102922-d636f9e8-c214-4218-8866-45aa3d8b3e14.png)
RDA
Kind regards,
Bartosz Kossowski

**Comment by wtclarke** [comment]
I'm going to close this, please reopen if you believe a bug remains in spec2nii.
