### ISSUE TITLE
Convert Siemens CSI from Twix or RDA

### ISSUE THREAD

**Issue by SamGuay** [wtclarke/spec2nii#68]
:wave: @wtclarke, 

I've used spec2nii to convert SVS and I really appreciate the usefulness of the tool, it's amazing thanks!

I've got access to CSI/MRSI data acquired on a Prisma (VD/VE IIRC) and I know it's not (yet) available for Twix and RDA data. Unfortunately, I only have the Twix and RDA, but not the dicoms. I've seen your message (`spec2nii.Siemens.rda.MRSINotHandledError: MRSI is currently not handled in the RDA format. Test data needed.`) and I could share some in private. I have both RDA and Twix of the same data.

It is probably not an easy (and quick?) feature to implement but I'd happily work on that feature if you are willing to give me some pointers to get me started.

Thanks

**Comment by wtclarke** [comment]
Hi @SamGuay,

I'd be very happy for you to contribute some code for the RDA CSI format. Twix is a more fundamental problem/decision as the data in .dat/twix is not reconstructed and there is currently no generalised way of doing so an arbitrary sequence.

What sort of pointers do you need? Are you happy with python and the concept of forking and submitting PRs on github?

Will

**Comment by SamGuay** [comment]
Hi! Thanks for the reply. It's been a while and I noticed that you've _worked_ on it (#69). I've started to dig a little into the code and get a more comprehensive idea CSI data. 

Regarding twix data, do you think the best way forward is to simply use spant's function [mrs_write_nifti.R](https://github.com/martin3141/spant/blob/master/R/mrs_write_nifti.R) to generate the file. I wish every thing could have been done in the same language.. I'll first test whether the output works with FSL-MRS, then decide if it's worth implementing it Python (unless you are already aware of a python-based tool).

That being said, I'll focus on implementing .RDA to get the ball rolling. I'm fine with the GH way of making PRs, etc. When I asked for pointers, I had more CSI pointers in mind but I think with the supported ones I can manage to understand what needs to be done!

Sam

**Comment by wtclarke** [comment]
Hi @SamGuay , does spant do the reconstruction of the data?

There is now a facility to create an empty NIfTI-MRS file for twix file. This should have all (or most) parameters filled in and the right data shape etc. You just have to insert the data post reconstruction.

**Comment by wtclarke** [comment]
Closing for now. Feel free to reopen, or contribute a PR for the RDA code.
