### ISSUE TITLE
Support for Philips MEGA-PRESS dicom

### ISSUE THREAD

**Issue by JonteP** [wtclarke/spec2nii#75]
Trying to convert mega-press data in dicom format currently produces the following error:

`Traceback (most recent call last):
  File "C:\Users\Jonpe389\Anaconda3\Scripts\spec2nii-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\Jonpe389\Anaconda3\lib\site-packages\spec2nii\spec2nii.py", line 664, in main
    spec2nii(*args)
  File "C:\Users\Jonpe389\Anaconda3\lib\site-packages\spec2nii\spec2nii.py", line 281, in __init__
    args.func(args)
  File "C:\Users\Jonpe389\Anaconda3\lib\site-packages\spec2nii\spec2nii.py", line 607, in philips_dicom
    self.imageOut, self.fileoutNames = multi_file_dicom(files_in, args.fileout, args.tag, args.verbose)
  File "C:\Users\Jonpe389\Anaconda3\lib\site-packages\spec2nii\Philips\philips_dcm.py", line 79, in multi_file_dicom
    mrs_type = svs_or_CSI(img)
  File "C:\Users\Jonpe389\Anaconda3\lib\site-packages\spec2nii\Philips\philips_dcm.py", line 39, in svs_or_CSI
    if _is_new_format(img):
  File "C:\Users\Jonpe389\Anaconda3\lib\site-packages\spec2nii\Philips\philips_dcm.py", line 34, in _is_new_format
    raise ValueError(f'Media Storage SOP Class UID {media_storage_class} not recognised as spectroscopy.')
ValueError: Media Storage SOP Class UID 1.3.46.670589.11.0.0.12.2 not recognised as spectroscopy.`

Unfortunately for some measurements I do not have data in SPAR/SDAT format so support for this would be tremendously helpful.

The dicom data seems to be one file per spectrum and looking through the header, it seems that the actual data is stored in '2005','1270'.

I can provide example data in both dicom and SPAR/SDAT for the same measurement if it is possible to share privately.

**Comment by wtclarke** [comment]
Hi @JonteP ,

Happy to have a look at this. Data would be appreciated, I can do private, but if you had the ability to get some phantom data to share publicly, that would be appreciated.

Any idea why you have the weird DICOM SOP Class UID?
As far as some searching suggests:
Private MR Spectrum Storage = 1.3.46.670589.11.0.0.12.1
Private MR Series Data Storage = 1.3.46.670589.11.0.0.12.2

Has this data been uploaded to a server somewhere / anonymised which might modify the headers, or is it straight from the scanner?

**Comment by JonteP** [comment]
> Hi @JonteP ,
> 
> Happy to have a look at this. Data would be appreciated, I can do private, but if you had the ability to get some phantom data to share publicly, that would be appreciated.
> 
> Any idea why you have the weird DICOM SOP Class UID? As far as some searching suggests: Private MR Spectrum Storage = 1.3.46.670589.11.0.0.12.1 Private MR Series Data Storage = 1.3.46.670589.11.0.0.12.2
> 
> Has this data been uploaded to a server somewhere / anonymised which might modify the headers, or is it straight from the scanner?

Hi,

Thanks for pointing that out! Turns out one of the dicom files did not belong to that sequence, hence the error. After removing that file, the conversion actually succeeded. However, all the warnings suggest that you would still need example data to validate this? I can probably get some phantom data, but that will likely take a week or so. Let me know if it is still needed.

**Comment by wtclarke** [comment]
Hi @JonteP I think I've got the validation data I need, but I haven't yet had a chance to integrate the tests (hence the warnings remain for now). Thank you for offering. I'll close this issue, but feel free to get back in contact if you need any more help.

**Comment by JonteP** [comment]
> Hi @JonteP I think I've got the validation data I need, but I haven't yet had a chance to integrate the tests (hence the warnings remain for now). Thank you for offering. I'll close this issue, but feel free to get back in contact if you need any more help.

Thank you for helping out!

**Comment by JonteP** [comment]
> Hi @JonteP I think I've got the validation data I need, but I haven't yet had a chance to integrate the tests (hence the warnings remain for now). Thank you for offering. I'll close this issue, but feel free to get back in contact if you need any more help.

Not sure if this is at all helpful, but I compared nifti-files converted from SPAR/SDAT vs philips old dicom format. The below parameters differed in the resulting nifti header, mostly flipped signs and reordered values. Also, the data is sorted differently in the nifti files, off and on spectra are grouped in the SDAT-nifti but interleaved in the dcm-nifti, causing at least Osprey to fail processing the latter.

From SPAR/SDAT
         qform_code: 2
         sform_code: 2
         quatern_b: -0.1412
         quatern_c: 0.0044
         quatern_d: 0.0265
         qoffset_x: 3.1312
         qoffset_y: 30.8834
         qoffset_z: 46.3264
         srow_x: [39.9422 -2.1484 0.0256 3.1312]
         srow_y: [2.0482 38.3485 5.5423 30.8834]
         srow_z: [-0.6504 -11.1704 19.0221 46.3264]

From DICOM
        qform_code: 2
        sform_code: 2
        quatern_b: 0.0044
        quatern_c: 0.1412
        quatern_d: -0.9896
        qoffset_x: -3.1312
        qoffset_y: -30.8834
        qoffset_z: 46.3264
        srow_x: [-39.9422 2.1484 -0.0256 -3.1312]
        srow_y: [-2.0482 -38.3485 -5.5423 -30.8834]
        srow_z: [-0.6504 -11.1704 19.0221 46.3264]

**Comment by wtclarke** [comment]
Thanks, thats useful to know about the dcm/spar mismatch currently. The aim of the validation will be to make sure these line up.

The interleaved issues arises from the fact that DICOM typically contains no information about the scan ordering, so in general it's just formed into a long list. There is the `mrs_tools reshape` command that can help sort this out. Which sequence is this? Is it a vendor standard MEGA-PRESS, something custom, or something custom with wide distribution e.g. something from JohnsHopkins. It might be possible to put some special casing in for it.

**Comment by JonteP** [comment]
> Thanks, thats useful to know about the dcm/spar mismatch currently. The aim of the validation will be to make sure these line up.
> 
> The interleaved issues arises from the fact that DICOM typically contains no information about the scan ordering, so in general it's just formed into a long list. There is the `mrs_tools reshape` command that can help sort this out. Which sequence is this? Is it a vendor standard MEGA-PRESS, something custom, or something custom with wide distribution e.g. something from JohnsHopkins. It might be possible to put some special casing in for it.

This should be Philips official sequence, but I believe the order changed after an upgrade. In the old version at least, the spectra are ordered as collected [ref, off, on, off, on, off, on, off, on]. Maybe it's possible to have an option to manually specify the spectrum order in spec2nii?
Anyway, I got identical results on Osprey after reordering the spectra in the nifti and also multiplying srow_x and srow_y by -1.
