### ISSUE TITLE
Some files are perhaps unintentionally not distributed

### ISSUE THREAD

**Issue by musicinmybrain** [wtclarke/spec2nii#77]
- `CHANGELOG.md` should probably be in the PyPI sdist
- `spec2nii/GE/VESPA_LICENSE` should definitely be in the PyPI sdist and the wheels, since it is referenced in the main `LICENSE` file
- either the tests should be omitted from the PyPI sdist, or all the necessary files should be included: currently, `tests/__init__.py`, `tests/io_for_tests.py`, and `tests/pytest.ini` are missing from the PyPI sdist

**Comment by wtclarke** [comment]
This should be fixed with the PR merged and released in v0.6.9

**Comment by musicinmybrain** [comment]
> This should be fixed with the PR merged and released in v0.6.9

Thanks!

One follow-up regarding the tests: https://github.com/wtclarke/spec2nii/pull/80
