### ISSUE TITLE
SPEC2NII Returns 0 Units

### ISSUE THREAD

**Issue by JBarsotti** [wtclarke/spec2nii#82]
Hi all,

I thought that I had successfully converted DICOM to NIFTI for my MRS data. However, when I looked at the xyzt units in the NIFTI header, it showed that there were 0 units. Is there an issue with conversion for certain types of DICOM?

Thanks.

**Comment by wtclarke** [comment]
Hi @JBarsotti could you give more details? Exactly what was zero in the NIfTI header? Could you give the output of `spec2nii dump your_converted_file.nii.gz`? What was the source of this DICOM?

**Comment by JBarsotti** [comment]
Thank you for the reply!

This is what the header file looks like:

![image](https://github.com/wtclarke/spec2nii/assets/75189583/21c34768-a825-4307-b469-d45f0058acbd)

Note that xyzt_units() = 0. I would expect this to be in Hz since the file I was convering was an MRS file.

**Comment by wtclarke** [comment]
It does look like I should make sure this reports the right units, in this case seconds for the 4th dimension (stored in the time domain). What command did you run to convert this file?

**Comment by JBarsotti** [comment]
I used the following commnad:

**spec2nii ge -j /filepath/Pfile.7 -o /outputPath**

I should note that I had to edit the GE ge_pfile.py and the ge_read_pfile.py so that they would recognize the "probe-sl" scan type.

**Comment by wtclarke** [comment]
Ok, I'll make a note to make a change in the NIfTI-MRS software to ensure that these codes are set properly. This should be a change around https://github.com/wtclarke/nifti_mrs_tools/blob/master/src/nifti_mrs/create_nmrs.py#L148 and in the validator.

**Comment by wtclarke** [comment]
Also was the `probe-sl` sequence you are using single voxel? I haven't come across that yet, only an MRSI version. Is it semi-laser?

**Comment by JBarsotti** [comment]
It is a single voxel acquisition. The sequence can be run as a single voxel or multi-voxel acquisition. It is a semi-laser sequence.

**Comment by wtclarke** [comment]
Any chance you could share some example data for ongoing testing? Just a simple scan on a phantom would be ideal.

**Comment by JBarsotti** [comment]
May I email you the file? It is a ".7" file, which GitHub doesn't support.

**Comment by wtclarke** [comment]
Of course. ***@***.***
________________________________

**Comment by wtclarke** [comment]
Hi @JBarsotti,

The xyzt_units issue should be fixed by updating the nifti-mrs package to v1.0.1 (on pypi now, conda shortly). I was then trying to fix the pipeline for the data you provided me, but the data size is different to that calculated from the headers. Could you tell me a bit more about the acquisition so I cant ry and figure out where it is going wrong? What version software was it acquired on? And a basic check, should the file be about 3.4 MB on disk?

**Comment by wtclarke** [comment]
Or actually could you tell me what edits you made: "I should note that I had to edit the GE ge_pfile.py and the ge_read_pfile.py so that they would recognize the "probe-sl" scan type."

**Comment by JBarsotti** [comment]
I will have to get back to you on the data. It is from an experiment someone else did, not me.

**Comment by wtclarke** [comment]
@JBarsotti Thanks. What were the edits you made? That might be sufficient to get me on the right path.

**Comment by JBarsotti** [comment]
Okay, sorry if this is a bit vague, but I don't have the code in front of me right now (technical computer issues). I know for sure I added ‘probe-sl’ to line 183 of the ge_read_pfile.py. I also added it to the "if" loop at approximately line 100 of ge_pfile.py. That is all I did.

**Comment by wtclarke** [comment]
@JBarsotti Hi, unfortunately I never got this to work. If you had time, I'd be very appreciative if you could confirm whether either the official version or a modified version of spec2nii now works with your data.

**Comment by wtclarke** [comment]
Closing this given the inactivity. If you would like to reopen then I am happy to take a further look with more help.
