### ISSUE TITLE
converting RDA results in UnicodeDecodeError

### ISSUE THREAD

**Issue by gaunab** [wtclarke/spec2nii#96]
When I try to convert a Siemens RDA-File I get the following Error:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 27: invalid start byte`

The Error is raised by:
`spec2nii/Siemens/rda.py", line 47, in convert_rda`

**Comment by wtclarke** [comment]
This is fixed in #115 and will be in version 0.7.1
